--FOR ESRB_RATING

-- FROM A GIVEN GAMEID , SELECT ESRB_RATING
SELECT ER.NAME ESRB_RATING 
FROM ESRB_RATING er JOIN ESRBRATING_GAME eg ON ER.ID = EG.ESRBRATING_ID 
WHERE EG.GAMEID =3498;

-- FIND ALL THE GAME NAME ACCORDING TO A FIXED ESRB_RATING (SLUG)
SELECT G.NAME GAME_NAME
FROM GAME g JOIN ESRBRATING_GAME eg ON G.ID = EG.GAMEID  
WHERE EG.ESRBRATING_ID = (SELECT ER.ID FROM ESRB_RATING er WHERE ER.SLUG='mature');

--COUNT THE NUMBER OF GAMES HAVING A FIXED ESRB_RATING
SELECT COUNT(G.NAME) NUMBER_OF_GAMES
FROM GAME g JOIN ESRBRATING_GAME eg ON G.ID = EG.GAMEID  
WHERE EG.ESRBRATING_ID = (SELECT ER.ID FROM ESRB_RATING er WHERE ER.SLUG='mature');

--FIND THE NUMBER OF GAMES OF ALL ESRB_RATING (COUNT OF EVERYONE ESRB_RATING IS 0, IT ISN'T SHOWN HERE. HOW? )
SELECT ER.NAME ESRB_RATING , COUNT(EG.GAMEID) NUMBER_OF_GAMES
FROM ESRB_RATING er JOIN ESRBRATING_GAME eg ON ER.ID =EG.ESRBRATING_ID 
GROUP BY(ER.NAME)
ORDER BY ER.NAME ASC;

-- ------------------------------------------------------------------------------------------------------------------

-- FOR SHORT SCREENSHOT
-- SELECT SS OF A GAME (GIVEN GAMEID)
SELECT SS.IMAGE "SHORT SCREENSHOT"
FROM SHORT_SCREENSHOT ss 
WHERE SS.GAMEID = 3498;

-- SELECT SS OF A GAME (GIVEN NAME)
SELECT SS.IMAGE "SHORT SCREENSHOT"
FROM SHORT_SCREENSHOT ss JOIN GAME g ON G.ID = SS.GAMEID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-') ;

-- --------------------------------------------------------------------------------------------------------------------

-- FOR ADDED_BY_STATUS

-- SELECT ALL ADDED_BY_STATUS OF A GAME GIVEN GAMEID
SELECT G.NAME GAME_NAME, ABS2.YET, ABS2.OWNED , ABS2.BEATEN, ABS2.TOPLAY , ABS2.DROPPED , ABS2.PLAYING 
FROM ADDED_BY_STATUS abs2 JOIN GAME g ON G.ID = ABS2.GAMEID 
WHERE G.ID = 3498;

-- SELECT ALL ADDED_BY_STATUS OF A GAME GIVEN GAME_NAME
SELECT G.NAME GAME_NAME, ABS2.YET, ABS2.OWNED , ABS2.BEATEN, ABS2.TOPLAY , ABS2.DROPPED , ABS2.PLAYING 
FROM ADDED_BY_STATUS abs2 JOIN GAME g ON G.ID = ABS2.GAMEID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-') ;

-- ORDER THE GAME ACCORDING TO THE DESCENDING NUMBER OF YET
SELECT G.NAME  GAME_NAME, ABS2.YET 
FROM GAME g JOIN ADDED_BY_STATUS abs2 ON ABS2.GAMEID =G.ID 
ORDER BY ABS2.YET DESC;

-- ORDER THE GAME ACCORDING TO THE DESCENDING NUMBER OF OWNED
SELECT G.NAME  GAME_NAME, ABS2.OWNED
FROM GAME g JOIN ADDED_BY_STATUS abs2 ON ABS2.GAMEID =G.ID 
ORDER BY ABS2.OWNED DESC;

-- ORDER THE GAME ACCORDING TO THE DESCENDING NUMBER OF BEATEN
SELECT G.NAME  GAME_NAME, ABS2.BEATEN 
FROM GAME g JOIN ADDED_BY_STATUS abs2 ON ABS2.GAMEID =G.ID 
ORDER BY ABS2.BEATEN  DESC;

-- ORDER THE GAME ACCORDING TO THE DESCENDING NUMBER OF TOPLAY
SELECT G.NAME  GAME_NAME, ABS2.TOPLAY
FROM GAME g JOIN ADDED_BY_STATUS abs2 ON ABS2.GAMEID =G.ID 
ORDER BY ABS2.TOPLAY DESC;

-- ORDER THE GAME ACCORDING TO THE ASCENDING NUMBER OF DROPPED
SELECT G.NAME  GAME_NAME, ABS2.DROPPED
FROM GAME g JOIN ADDED_BY_STATUS abs2 ON ABS2.GAMEID =G.ID 
ORDER BY ABS2.DROPPED ASC;

-- ORDER THE GAME ACCORDING TO THE DESCENDING NUMBER OF PLAYING
SELECT G.NAME  GAME_NAME, ABS2.PLAYING
FROM GAME g JOIN ADDED_BY_STATUS abs2 ON ABS2.GAMEID =G.ID 
ORDER BY ABS2.PLAYING DESC;

-- GET THE NUMBER OF ADDED COUNT OF A FIXED GAME
SELECT G.NAME , G.ADDED_COUNT 
FROM GAME g 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-') ; 

-- --------------------------------------------------------------------------------------------
-- FOR RATING LEVEL

-- FIND THE RATING TITLE OF A GAME GIVEN NAME
SELECT G.NAME GAME_NAME, RL.TITLE RATING_TITLE
FROM GAME g JOIN GAME_RATING gr ON G.ID = GR.GAMEID 
JOIN RATING_LEVEL rl ON RL.ID =GR.RATINGID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-') ; 

-- FIND RATING COUNT AND PERCENT OF A GAME
SELECT G.NAME , GR.RATING_COUNT , GR.PERCENT 
FROM GAME g JOIN GAME_RATING gr ON G.ID = GR.GAMEID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-') ; 

-- -------------------------------------------------------------------------------------------
-- FOR GENRE

-- FIND GENRE OF A SPECIFIC GAME 
SELECT G.NAME GAME_NAME, G2.NAME GENRE 
FROM GAME g JOIN GAME_GENRE gg ON GG.GAMEID =G.ID 
JOIN GENRE g2 ON G2.ID =GG.GENRE_ID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-') ; 

-- NUMBER OF GAMES OF A GIVEN GENRE
SELECT G.NAME GENRE, G.GAMES_COUNT ,G.IMAGE_BACKGROUND 
FROM GENRE g 
WHERE G.SLUG = REPLACE(LOWER('ACTION'),' ','-') ; 

-- NAME OF THE GAMES OF A GIVEN GENRE
SELECT G2.NAME GENRE , G.NAME GAME_NAME
FROM GAME g JOIN GAME_GENRE gg ON GG.GAMEID =G.ID 
JOIN GENRE g2 ON G2.ID =GG.GENRE_ID 
WHERE G2.SLUG = REPLACE(LOWER('ACTION'),' ','-') ; 

-- NUMBER OF GAMES OF ALL GENRE 
SELECT G.NAME GENRE, G.GAMES_COUNT , G.IMAGE_BACKGROUND 
FROM GENRE g 
ORDER BY G.GAMES_COUNT DESC;

-- ------------------------------------------------------------------------
-- FOR PARENT PLATFORM

-- NAME OF THE GAMES FOR A GIVEN PARENT PLATFORM
SELECT PP.NAME PARENT_PLATFORM , G.NAME GAME_NAME
FROM GAME g JOIN GAME_PARENTPLATFORM gp ON G.ID=GP.GAMEID 
JOIN PARENT_PLATFORM pp ON PP.ID =GP.PARENTPLATFORM_ID 
WHERE PP.SLUG = REPLACE(LOWER('XBOX'),' ','-');

-- NAME OF THE PARENT PLATFORMS FOR A GIVEN GAME
SELECT G.NAME GAME_NAME, PP.NAME PARENT_PLATFORM 
FROM GAME g JOIN GAME_PARENTPLATFORM gp ON G.ID=GP.GAMEID 
JOIN PARENT_PLATFORM pp ON PP.ID =GP.PARENTPLATFORM_ID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-');

-- NUMBER OF GAMES ON DIFFERENT PARENT PLATFORM
SELECT PP.NAME PARENT_PLATFORM , COUNT(G.NAME ) NUMBER_OF_GAMES
FROM GAME g JOIN GAME_PARENTPLATFORM gp ON G.ID=GP.GAMEID 
JOIN PARENT_PLATFORM pp ON PP.ID =GP.PARENTPLATFORM_ID 
GROUP BY PP.NAME 
ORDER BY PP.NAME ASC;

-- -------------------------------------------------------------------------------
-- FOR TAGS

-- SELECT TAGS OF A GIVEN GAME
SELECT G.NAME  GAME_NAME, T.NAME TAG 
FROM GAME g JOIN GAME_TAG gt ON GT.GAMEID =G.ID 
JOIN TAG t ON GT.TAG_ID =T.ID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-'); 

-- FIND LANGUAGE OF A GIVEN GAME
SELECT UNIQUE G.NAME GAME_NAME, T."LANGUAGE" 
FROM GAME g JOIN GAME_TAG gt ON GT.GAMEID =G.ID 
JOIN TAG t ON GT.TAG_ID =T.ID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-'); 

-- SELECT GAMES OF A GIVEN TAG
SELECT T.NAME  TAG, G.NAME GAME_NAME
FROM GAME g JOIN GAME_TAG gt ON GT.GAMEID =G.ID 
JOIN TAG t ON GT.TAG_ID =T.ID 
WHERE T.SLUG = REPLACE(LOWER('SINGLEPLAYER'),' ','-');

-- NUMBER OF GAMES OF DIFFERENT TAGS
SELECT T.NAME TAG, T.GAMES_COUNT NUMBER_OF_GAMES
FROM TAG t 
ORDER BY T.GAMES_COUNT DESC;

-- ---------------------------------------------------------------------------------------
-- FOR PUBLISHER

-- FIND PUBLISHER OF A GIVEN GAME
SELECT G.NAME GAME_NAME, P.NAME PUBLISHER_NAME, P.DESCRIPTION  PUBLISHER_DESCRIPTION
FROM GAME g JOIN PUBLISHER p ON G.PUBLISHERID = P.ID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-'); 

-- FIND NAME OF GAMES OF A GIVEN PUBLISHER
SELECT P.NAME PUBLISHER_NAME, G.NAME GAME_NAME, G.RELEASED RELEASED_DATE
FROM  GAME g JOIN PUBLISHER p ON G.PUBLISHERID = P.ID
WHERE P.NAME =' ';

-- FIND NUMBER OF GAMES PUBLISHED BY A PUBLISHER 
SELECT P.NAME , P.IMAGE , P.GAMES_COUNT 
FROM PUBLISHER p 
WHERE P.NAME ='';

-- ----------------------------------------------------------------------------------------
-- FOR STORE

-- FIND A SPECIFIC GAME'S STORE
SELECT G.NAME GAME_NAME, S.NAME STORE_NAME, S."DOMAIN" STORE_DOMAIN
FROM GAME g JOIN GAME_STORE gs ON GS.GAMEID =G.ID 
JOIN STORE s ON S.ID =GS.STORE_ID 
WHERE G.SLUG = REPLACE(LOWER('Grand Theft Auto V'),' ','-'); 

-- FIND THE GAMES ON A SPECIFIC STORE
SELECT S.NAME STORE_NAME, S."DOMAIN" STORE_DOMAIN, G.NAME GAME_NAME
FROM GAME g JOIN GAME_STORE gs ON GS.GAMEID =G.ID 
JOIN STORE s ON S.ID =GS.STORE_ID 
WHERE S.SLUG = REPLACE(LOWER('PlayStation Store'),' ','-'); 

-- --------------------------------------------------------------------------------------------
-- FOR PLATFORM 

-- FIND REQUIREMENTS OF A GAME IN A SPECIFIC PLATFORM
SELECT G.NAME GAME_NAME, P.NAME PLATFORM_NAME, POG.MINIMUM_REQUIREMENTS ,POG.RECOMMENDED_REQUIREMENTS 
FROM GAME g JOIN PLATFORM_ON_GAMES pog ON POG.GAMEID =G.ID 
JOIN PLATFORM p ON P.ID =POG.PLATFORMID 
WHERE G.SLUG =REPLACE(LOWER('Grand Theft Auto V'),' ','-');
AND P.SLUG = REPLACE(LOWER('PlayStation Store'),' ','-'); 

-- FIND PLATFORMS FOR A SPECIFIC GAME
SELECT G.NAME GAME_NAME, P.NAME PLATFORM_NAME
FROM GAME g JOIN PLATFORM_ON_GAMES pog ON POG.GAMEID =G.ID 
JOIN PLATFORM p ON P.ID =POG.PLATFORMID 
WHERE G.SLUG =REPLACE(LOWER('Grand Theft Auto V'),' ','-'); 

-- FIND GAMES FOR A SPECIFIC PLATFORM
SELECT G.NAME GAME_NAME, P.NAME PLATFORM_NAME
FROM GAME g JOIN PLATFORM_ON_GAMES pog ON POG.GAMEID =G.ID 
JOIN PLATFORM p ON P.ID =POG.PLATFORMID 
AND P.SLUG = REPLACE(LOWER('PlayStation Store'),' ','-'); 

-- ------------------------------------------------------------------------------------------------------------
-- WISHLIST

-- FIND WISHLIST OF A PERSION
SELECT P.NAME , G.NAME 
FROM PERSON p JOIN WISHLIST w ON W.PERSONID =P.ID 
JOIN GAME g ON G.ID=W.GAMEID 
WHERE P.NAME ='';

-- FIND PEOPLE WHO HAS KEPT A SPECIFIC GAME IN THEIR WISHLIST
SELECT G.NAME, P.NAME  
FROM PERSON p JOIN WISHLIST w ON W.PERSONID =P.ID 
JOIN GAME g ON G.ID=W.GAMEID 
WHERE G.SLUG  ='';

-- -----------------------------------------------------------------------------
-- FOR REVIEWS 
-- ALL REVIEWS WRITTEN BY A SPECIFIC PERSON
SELECT P.NAME ,(SELECT G.NAME FROM GAME g WHERE G.ID = R.GAMEID) GAME_NAME, R.RATING , R.REVIEW_TEXT 
FROM REVIEWS r JOIN PERSON p ON R.PERSONID =P.ID 
WHERE P.NAME ='';

-- ALL REVIEWS FOR A SPECIFIC GAME
SELECT (SELECT P.NAME FROM PERSON p WHERE P.ID=R.PERSONID) PERSON_NAME, R.RATING , R.REVIEW_TEXT 
FROM REVIEWS r JOIN GAME g ON R.GAMEID =G.ID 
WHERE G.SLUG ='';

-- TOTAL REVIEWS BY A PERSON
SELECT P.NAME , P.EMAIL , COUNT(R.GAMEID) TOTAL_REVIEWS
FROM REVIEWS r JOIN PERSON p ON P.ID =R.PERSONID 
WHERE P.NAME =''
GROUP BY (P.NAME, P.EMAIL);

--TOTAL REVIEW FOR A GAME
SELECT G.NAME , G.REVIEWS_COUNT 
FROM GAME g 
WHERE G.SLUG ='';

-- ------------------------------------------------------------------------------------------------------------
-- COLLECION

-- FIND COLLECTION OF A PERSION
SELECT P.NAME , G.NAME 
FROM PERSON p JOIN COLLECTION c  ON C.PERSONID =P.ID 
JOIN GAME g ON G.ID=C.GAMEID 
WHERE P.NAME ='';

-- FIND PEOPLE WHO HAS KEPT A SPECIFIC GAME IN THEIR COLLECTION
SELECT G.NAME, P.NAME  
FROM PERSON p JOIN COLLECTION c  ON C.PERSONID =P.ID 
JOIN GAME g ON G.ID=C.GAMEID 
WHERE G.SLUG  ='';

-- ----------------------------------------------------------------------------------
-- EVENT

-- EVENT BETWEEN A SPECIFIC DATE
SELECT (SELECT G.NAME  FROM GAME g WHERE G.ID=E.GAMEID)GAME_NAME, E.IMAGE , E.DESCRIPTION EVENT_DESCRIPTION
FROM EVENTS e 
WHERE E.EVENT_DATE BETWEEN ' ' AND '';

-- EVENT FOR A SPECIFIC GAME
SELECT G.NAME GAME_NAME, E.TITLE ,E.DESCRIPTION , E.EVENT_DATE , E.ORGANIZER  
FROM EVENTS e JOIN GAME g ON E.GAMEID =G.ID 
WHERE G.SLUG= REPLACE(LOWER('Grand Theft Auto V'),' ','-');

-- EVENTS PARTICIPATED BY A SPECIFIC PERSON
SELECT P.NAME PERSON_ANAME, E.TITLE EVENT_NAME
FROM PERSON p JOIN PARTICIPATION p2 ON P2.PERSONID =P.ID 
JOIN EVENTS e ON P2.EVENTID = E.ID 
WHERE P.ID ='';

-- PERSONS PARTICIPATE IN A EVENTS OF A SPECIFIC GAME 
SELECT (SELECT P2.NAME FROM PERSON p2 WHERE P2.ID=P.PERSONID)PERSON_NAME, G.NAME GAME_NAME, E.TITLE EVENT_NAME
FROM EVENTS e JOIN GAME g ON G.ID =E.GAMEID 
JOIN PARTICIPATION p ON P.EVENTID = E.ID 
WHERE G.SLUG ='';

-- -------------------------------------------------------------------------------------------
--NEWS

































